# Generated by Django 5.0.3 on 2024-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_planetariumdome_reservation_showtheme_showsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='show_themes',
            field=models.ManyToManyField(blank=True, to='planetarium.showtheme'),
        ),
    ]
